version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: carefleet-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: carefleet
    volumes:
      - mongodb_data:/data/db
      - ./backend/src/main/resources/db/init:/docker-entrypoint-initdb.d:ro
    networks:
      - carefleet-network

  redis:
    image: redis:7-alpine
    container_name: carefleet-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - carefleet-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: carefleet-backend
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATA_MONGODB_URI=mongodb://mongodb:27017/carefleet
      - SPRING_DATA_REDIS_HOST=redis
      - SPRING_DATA_REDIS_PORT=6379
    depends_on:
      - mongodb
      - redis
    networks:
      - carefleet-network

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: carefleet-frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - VITE_API_BASE_URL=http://localhost:8080/api/v1
    depends_on:
      - backend
    networks:
      - carefleet-network

volumes:
  mongodb_data:
  redis_data:

networks:
  carefleet-network:
    driver: bridge